### ISSUE TITLE
Bundle not implemented for <(A) as hecs::bundle::DynamicBundle>

### ISSUE THREAD

**Issue by Javagedes** [Ralith/hecs#14]
Hello, First of all, loving the project so far! 

I saw a possible issue, which I believe has to do with your tuple_impl! macro (or the macro that calls tuple_impl! for all the different combinations of (A,B, etc), though I'm not good with macros so I can't be sure.

As the title says, bundle is not implemented for (A). It's implemented for (A,); (A,B); etc..

**To reproduce:**
`
let mut storage = World::new();
let e = storage.spawn((1));
`

This is mainly problematic when attempting to use `storage.insert(...)` as I've found it common to want to add a single component to an entity at run time. It's currently trivial to work around; just use (A,) instead of (A). If it is intended functionality for it to be (A,), then I believe (A) would be more user friendly. However, in v1.6, tuple_impl! was used for (A), not (A,), so I assume this is just a small issue with the macros!

Just wanted to make you aware... again, loving hecs so far!

**Comment by Ralith** [comment]
Thanks for the feedback! This is working as intended. Unfortunately it's not possible to `impl<T: Component> DynamicBundle for T`, because this would conflict with practically all other implementations. That's why we expose the helper methods `insert_one` and `remove_one` on `World`.  I've tweaked the documentation in c86ecfcd3bdfc9651813e8acb35f19582d58a849 to hopefully make this more apparent!

**Comment by Ralith** [comment]
In case it wasn't clear, the key distinction here is that `(A,)` is a distinct type from `A`, but `(A)` and `A` are the same thing.
