### ISSUE TITLE
Use NonZeroU32 for entity generation.

### ISSUE THREAD

**Issue by zakarumych** [Ralith/hecs#172]
This is possible if generations start with 1. And this makes `Option<Entity>` and `Entity` sizes match.

**Comment by louisgjohnson** [comment]
I was just browsing the code to see how much work would be required for this, what happens if the generation starts with zero, should the generation value be None? So the generation typing should be `Option<NonZeroU32>`

for example the EntityMeta has a const value called Empty that returns 0 for the generation

**Comment by zakarumych** [comment]
The generation should never be 0.

**Comment by Ralith** [comment]
Implemented in #190.
