### ISSUE TITLE
Main Thread Panicked: Already borrowed uniquely

### ISSUE THREAD

**Issue by ricardoalcantara** [Ralith/hecs#179]
Hello, I am trying to execute a query inside another query. Like that?

```rust
for (_entity, (actor, transform, collition)) in &mut world.query::<(&mut Actor, &mut Transform2D, Option<&Collision>)>() {
        let mut other_actors = Vec::new();

        if actor.move_x != 0.0 || actor.move_y != 0.0 {
            for rect in world
                .query::<(&Collision, &Transform2D)>()
                .iter()
                .filter(|(other_entity, _)| *other_entity != _entity)
                .map(|(_other_entity, (collision, other_transform))| Rectangle::new(
                    collision.rectangle.x + other_transform.position.x,
                    collision.rectangle.y + other_transform.position.y,
                    collision.rectangle.width,
                    collision.rectangle.height,
                ))
            {
                other_actors.push(rect);
            }
        }

      // ... there's more things ...
}
```
however even though I tried to filter with id1 != id0 like you did on you examples https://github.com/Ralith/hecs/blob/master/examples/ffa_simulation.rs#L82 it panicked.

Is there anyway to query all other entities but the current one?

**Comment by Ralith** [comment]
This was discussed on the gamedev discord, but for posterity: No, concurrent queries with conflicting borrows are not supported. The example works because its borrows don't conflict, because they're shared (aka immutable), whereas you're starting out with a unique (aka mutable) borrow of `Transform2D`, then trying to get another.

Alternative approaches include:
- Don't use nested queries. As discussed in the README and in the comment just above your link, they're a wasteful solution to the problem of collision detection.
- Don't use a mutable borrow in either query. If you need to make changes in a nested query, accumulate a list of changes to make in a `Vec` then apply it in a separate pass.

**Comment by ricardoalcantara** [comment]
Understood! Thanks for the time.
