### ISSUE TITLE
AtomicU64/AtomicI64 not supported on 32-bit mips/ppc

### ISSUE THREAD

**Issue by sajattack** [Ralith/hecs#204]
https://doc.rust-lang.org/std/sync/atomic/#portability

```
PowerPC and MIPS platforms with 32-bit pointers do not have `AtomicU64` or
//!   `AtomicI64` types.
```

You're using AtomicU64/AtomicI64 in two places https://github.com/Ralith/hecs/blob/270e3f60dd2ef2291a774b25c0e34106de7302f5/src/entities.rs#L174
https://github.com/Ralith/hecs/blob/2c1dbcb6d60f7ed83e58677c53ea829cd2780ecb/src/world.rs#L57

Which breaks compatibility for these platforms. 

I worked around it by changing to Atomic[I|U]Size in this patch https://bpa.st/OGYA

If you have another idea to solve, let me know.

**Comment by Ralith** [comment]
Switching the entity alloc cursor to `AtomicIsize` seems very sensible. The world ID value is trickier, since 32 bits are small enough that a long-lived application which could rapidly rebuild worlds might run into a limit. `Mutex<u64>` would solve this, but breaks no-std. We could fake a u64 with two u32s and a CAS loop; in principle that makes it difficult to guarantee forward progress, but given that `World::new` shouldn't be getting hit *that* hard maybe it's fine?

**Comment by sajattack** [comment]
Perhaps this is a good option https://crates.io/crates/atomic-shim

**Comment by Ralith** [comment]
A mutex from https://github.com/mvdnes/spin-rs should do the trick, I think.
