### ISSUE TITLE
Remove Any

### ISSUE THREAD

**Issue by ElchananHaas** [Ralith/hecs#239]
Currently World has remove which will efficiently remove many components, but fails if any of them are not present. Add a function similar to remove that succeeds as long as the entity is present in world and removes all components in the bundle type without repeated reallocation.

**Comment by Ralith** [comment]
Is repeated calling of `remove_one` insufficient for your purposes?

**Comment by Ralith** [comment]
I'm reluctant to support microopts for niche cases, especially when it's unclear if additional performance solves any problems. Such a method would not be generally applicable, since not all applications call for silently ignoring missing components, and some applications benefit from access to the removed component, which is not possible in the proposed model.

**Comment by ElchananHaas** [comment]
Ok
