### ISSUE TITLE
Confused with different query methods

### ISSUE THREAD

**Issue by pherrymason** [Ralith/hecs#343]
First of all, I'm not yet very versed with Rust, so I maybe I'm missing some more experience with the language itself.
Second, this is not a complain, I'm just trying to point some possible issues in the documentation as a newbie. 

I'm not very sure to understand when to use `query` or `query_mut`.  
Solely on the name, I infer that if I need to mutate some entities I should use `query_mut`. However, `query` docs say I can request `&mut T`. 

Documentation on `query_mut` says:

> Query a uniquely borrowed world
> Like [query](https://docs.rs/hecs/0.10.3/hecs/struct.World.html#method.query), but faster because dynamic borrow checks can be skipped

As someone who is a new user of the library and rust, I miss some higher level description. I totally understand a more experienced Rust developer will be interested also in those technical details mentioned there, but I'm not there yet :'(

Also, why `query` and does not implement `IntoIter`?

I guess the same applies to `query_one` and `query_one_mut`?

**Comment by adamreichold** [comment]
> Solely on the name, I infer that if I need to mutate some entities I should use query_mut. However, query docs say I can request &mut T.

The point is not what you can with the queried components, but whether you have a mutable reference to the `World` which you query because this allows hecs to skip checking whether your query conflicts with other currently active queries because there can only be one mutable reference and hence only one active query. (It has been argued that "mutable reference" is a misnomer and it should have been "exclusive reference" instead.)

As a rule of thumb, `query` and `query_mut` give you equivalent capabilities but `query_mut` is more efficient. Hence you `query_mut` when you can and `query` when you must. But then again, premature optimization is the root of all evil you are probably best served by using `query` everywhere and only investigate switching to `query_mut` after having identified a performance bottleneck through profiling.

> Also, why query and does not implement IntoIter?

You probably mean why `QueryBorrow` (the return value of `World::query`) does not implement `IntoIterator`? If so, the answer is that `QueryBorrow` needs to outlive the elements returned by the iterator exactly to ensure concurrent access to components via multiple queries does not conflict, c.f. https://docs.rs/hecs/latest/src/hecs/query.rs.html#587

**Comment by pherrymason** [comment]
Thank you for your detailed description!

So, if I understand this well...
`query_mut` is the mechanism I have to tell hecs, the world I have available is a mutable reference. 

Can those conflict checks be skipped because the borrow checker rules ensure that no other mutable reference is alive and will compete with the query?

> You probably mean why QueryBorrow (the return value of World::query) does not implement IntoIterator?
Yeah, totally.

**Comment by adamreichold** [comment]
> Can those conflict checks be skipped because the borrow checker rules ensure that no other mutable reference is alive and will compete with the query?

Exactly. The basic borrowing rules apply either many shared references or a single mutable references. And the exclusiveness of mutable references can not only be used to modify memory, but also to skip additional synchronization that would be required without these additional guarantees provided by the borrow checker.

A much simpler application of these ideas is [`Mutex::get_mut`](https://doc.rust-lang.org/stable/std/sync/struct.Mutex.html#method.get_mut) where you gain access to the value protected by a mutex without locking it provided that you have obtain a mutable reference to the mutex itself. If you have that, it is necessarily the only one and no other shared references can exist which could be used to lock the mutex and apply conflicting modifications to the protected value.

**Comment by Ralith** [comment]
Closing as the questions here seem to be answered.
