### ISSUE TITLE
Best way to connect assets (e.g. sprites) to components?

### ISSUE THREAD

**Issue by canadaduane** [Ralith/hecs#38]
What's the best way to connect assets (e.g. sprites) to components?

I'm trying to add an Image (in this case, an Image from `good-web-game`) as one of an entity's components:

```
impl MainState {
    fn new(ctx: &mut Context) -> GameResult<MainState> {
        let assets = Assets::new(ctx)?;
        let mut world = World::new();
        world.spawn((Transform::new(), assets.player_image));
        ...
    }
}
```

But I get this as a result (and my Rust-fu is not great enough to understand what's going on):

```
error[E0277]: `std::cell::Cell<bool>` cannot be shared between threads safely
  --> src/main.rs:57:15
   |
57 |         world.spawn((Transform::new(), assets.player_image));
   |               ^^^^^ `std::cell::Cell<bool>` cannot be shared between threads safely
   |
   = help: within `gwg::graphics::Image`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<bool>`
   = note: required because it appears within the type `gwg::graphics::Image`
   = note: required because of the requirements on the impl of `hecs::world::Component` for `gwg::graphics::Image`
   = note: required because of the requirements on the impl of `hecs::bundle::DynamicBundle` for `(game::transform::Transform, gwg::graphics::Image)`
```

Any suggestions?

**Comment by Ralith** [comment]
It sounds like the image type you're trying to use is not thread safe. hecs allows the `World` to be shared between threads, and must pass that requirement along to components, which *usually* a non-issue. You could ask the author to replace the `Cell<bool>` with an `AtomicBool` if that's really the only issue, though there may be deeper reasons why they're not already using that. Alternatively, you could store your images in a [slab](https://crates.io/crates/slab) or similar structure, then put the keys inside the `hecs::World` instead of the values themselves.

**Comment by canadaduane** [comment]
Thanks, I made a PR to good-web-game and with that change, I think I have a strategy for making assets static (using Box::leak).

**Comment by Ralith** [comment]
Glad you got it working! You might also consider a slab approach (or even just putting them in a `Vec`) as a more principled solution to lifetime management, too.
