### ISSUE TITLE
Maybe unsound in 'get_mut'

### ISSUE THREAD

**Issue by lwz23** [Ralith/hecs#385]
I am not sure whether there is a unsound problem in the following function https://github.com/Ralith/hecs/blob/96f8289752318bea1040a04e082c92b65ece6950/src/query.rs#L1372
```
/// Retrieve the query results corresponding to `entity`
    ///
    /// Will yield `None` if the entity does not exist or does not match the query.
    pub fn get_mut(&mut self, entity: Entity) -> Option<Q::Item<'_>> {
        unsafe { self.get_unchecked(entity) }
    }
```
The potential bug in this code arises from the use of unsafe { self.get_unchecked(entity) } without explicitly verifying the validity of the entity. If entity is invalid, does not exist, or does not match the query, get_unchecked may result in undefined behavior (UB), such as accessing out-of-bounds memory or creating invalid references.

Although the function's comment promises to return None for invalid entities, there is no visible safety guarantee or boundary check in the implementation. This discrepancy could lead to unsoundness if get_unchecked fails to enforce these invariants internally.

sorry I don't have time to write a Poc to test whether it is a real unsound problem :( 
please don't be mind if I made a mistake.

**Comment by adamreichold** [comment]
Entities which do not match the query are already filtered out here because only matching archetypes have a `Some` in `self.fetch`. Furthermore, `get_unchecked` checks if the entity ID is valid and current.

Long story short, `get_unchecked` will do all those checks. The `unsafe` part about it is not missing bounds checks, but missing static checks whether the requested borrowing mode is sound which in this case it is because of the exclusive reference in `&mut self` limiting the lifetime of `Q::Item<'_>`.

**Comment by Ralith** [comment]
In particular, refer to the safety comment on `get_unchecked` and note what is *not* required.
