### ISSUE TITLE
parallel iteration

### ISSUE THREAD

**Issue by Extrawurst** [Ralith/hecs#42]
is it possible to iterate over a query in parallel? is it possible to iterate two query's in parallel if their component query does not interfere? if so how?

**Comment by Ralith** [comment]
> is it possible to iterate over a query in parallel?

This has been pretty much waiting for someone to ask for it. My plan is to expose a `batched_iter` method that takes `batch: usize` and yields an iterator that yields a series of query iterators that each yield at most `batch` elements. The inner iterators can then be sent to a threadpool such as rayon and processed in parallel. If this would address your need, I can implement it in the next few days.

> is it possible to iterate two query's in parallel if their component query does not interfere? if so how?

Yes, and "don't interfere" is very generous; it is legal to run two queries concurrently so long as they will never both select the same entity, even if the sets of components they borrow would otherwise be incompatible. `World` is `Sync` and `World::query` takes `&self`, so this should Just Work.

Note that attempting to iterate over *incompatible* queries in parallel will introduce a racey panic, so use care.

**Comment by Extrawurst** [comment]
>  If this would address your need, I can implement it in the next few days.

That would be amazing. Any reason why this wasn't a use case for you yet?

**Comment by Ralith** [comment]
I've never had trivially parallelizable per-entity game logic that was slow enough to justify it. I find that involving threadpools where they're not strictly necessary tends to be detrimental.

**Comment by Ratysz** [comment]
>This has been pretty much waiting for someone to ask for it.

I was going to, once I understood my requirements better. So far, `batched_iter` seems like it should work perfectly with what I've been doing.

Speaking of which, my [extension](https://github.com/Ratysz/yaks/) for `hecs` is now passing basic [parallelization tests](https://github.com/Ratysz/yaks/blob/master/tests/executor_parallel.rs), so iterating two queries in parallel is definitely possible. (I have most of the plumbing needed to detect if systems are disjoint over archetypes, just need to play around with how `hecs` could expose the required information; I'll share what I have in #13.)
