### ISSUE TITLE
Instanced renderer?

### ISSUE THREAD

**Issue by yohandev** [Ralith/hecs#70]
Since hecs doesn't have any shared components/tags feature, would there be any way to implement an "efficient" renderer, let alone an instanced renderer?

With a regular query, I could achieve something like this:
```rust
for (id, (ltw, mesh, pip)) in world.query::<(&LocalToWorld, &Mesh, &Pipeline)>().iter()
{
    // no instanced rendering here, just update the uniform buffer for every object
    ctx.update_uniform(ltw);

    // this is a relatively expensive operation
    // the `Mesh` component is a handle to a shared mesh
    ctx.bind_mesh(mesh);

    // also a relatively expensive operation
    // the `Pipeline` component is a handle to a shared graphics pipeline
    ctx.bind_pipeline(pip);

    // draw a single "instance"
    ctx.draw(0..1);
}
```
The code above would be ridiculously inefficient because both the mesh and pipeline are re-bound for every entity. Ideally, I'd like to be able to achieve something like this:
```rust
for chunk in world.query::<(&LocalToWorld,)>()
                                      .shared::<(&Mesh, &Pipeline)>()
                                      .iter()
{
    let mesh: &Mesh = chunk.shared_component::<Mesh>().unwrap();
    let pip: &Pipeline = chunk.shared_component().unwrap();

    // only bind once per chunk
    ctx.bind_mesh(mesh);

    // only bind once per chunk
    ctx.bind_pipeline(pip);

    for (id, (ltw,)) in chunk.iter()
    {
        // still not instanced, but much better than before
        ctx.update_uniform(ltw);
        ctx.draw(0..1);
    }
}
```

And even better, instanced rendering by getting a slice of components:
```rust
for chunk in world.query::<(&LocalToWorld,)>()
                                      .shared::<(&Mesh, &Pipeline)>()
                                      .iter()
{
    let mesh: &Mesh = chunk.shared_component::<Mesh>().unwrap();
    let pip: &Pipeline = chunk.shared_component().unwrap();

    // get a slice of components(I'm not sure how hecs stores component
    // data and if this is possible at all)
    let ltw: &[LocalToWorld] = chunk.components();

    // only bind once per chunk
    ctx.bind_mesh(mesh);

    // only bind once per chunk
    ctx.bind_pipeline(pip);

    // update buffer once
    ctx.update_uniform(ltw);

    ctx.draw(0..chunk.count());
}
```

So far, this has all been very similar to `legion`'s approach towards this problem. I'd be interested in any other methods that require less/no change to hecs' current API.

**Comment by Ralith** [comment]
Thanks for the issue! This is an interesting question, as I'm open to adding shared components if a sufficiently compelling use case emerges. That said, my approach would be to aggregate from the query directly into memory-mapped instance buffers:
```rust
let mut instance_buffers = ...;
for (id, (ltw, mesh, pip)) in world.query::<(&LocalToWorld, &Mesh, &Pipeline)>().iter()
{
    instance_buffers[pip][mesh].push(ltw);
}
for (pipeline, meshes) in instance_buffers {
    ctx.bind_pipeline(pipeline);
    for (mesh, instances) in meshes {
        ctx.bind_mesh(mesh);
        ctx.bind_instances(instances);
        ctx.draw(instances.len());
    }
}
```
`instance_buffers` could be a `HashMap<(Pipeline, Mesh), InstanceBuffer>` or, with slightly more bookkeeping, a `Vec<Vec<InstanceBuffer>>`.

This theoretically could suffer from reduced write locality, but I'd like to see a benchmark of a real case where that presents an issue. Conversely, this has the benefit that you can easily schedule the transfer of instance data to device-local memory all at once, imposing a single memory barrier, rather than repeatedly interleaving transfers and draws, and you don't sacrifice the ability to perform CPU culling.

With modern graphics devices, you may even be able to use descriptor indexing to use instancing where previously CPU-side rebinding would be necessary to e.g. change sets of textures, which will help keep locality up.

**Comment by yohandev** [comment]
That's a very interesting workaround, which I think I'll use on my current project! I think shared components could still be something hecs would benefit from, but for now, your approach seems viable.

**Comment by Ralith** [comment]
They're definitely an interesting notion, and I'll happy to discuss further prospective applications for them. I'll close this for now since it sounds like this particular use case is adequately addressed without, but feel free to open new issues for different cases, or reopen if issues arise with the proposed solution here.
