### ISSUE TITLE
Add support for generic types to `#[derive(Bundle)]`

### ISSUE THREAD

**Issue by sdleffler** [Ralith/hecs#87]
At current, the `Bundle` derive macro doesn't support generics and it seems to me like it should be able to support them without too much trouble.

**Comment by Veykril** [comment]
I took a look at this and there is a small problem. Due to the use of `lazy_static!` inside of the `hecs::Bundle` implementation when using generic parameters the derive macro will run into a compile time error as lazy_static tries to access a generic parameter outside of its defining `impl`(due to how lazy_static works, it generates a new type and impl for the static), see here for an example-ish output and the offending line [gist](https://gist.github.com/Veykril/567abf577b486af0a4a326890ed331df#file-hecs-rs-L46).

One solution would be to use [once_cell](https://docs.rs/once_cell/1.4.1/once_cell/) as its initialization function is just a closure which would be local to the trait impl(i think). The problem is that non-std once_cell doesn't have any sync cell so using that in a static won't really help in the end.

**Comment by Ralith** [comment]
Thanks for looking into this! Unfortunately, I'm not sure rust currently has any way to define a static that depends on a type variable. I'm fine with falling back on dynamically constructed arrays for generics for the time being, same as we do for tuples; once rust updates make it possible I hope to refactor `Bundle`'s interface to be completely `const` anyway.
